ARG SWIFT_VERSION=6.0.3
ARG DISTRIBUTION_VERSION=jammy
FROM swift:${SWIFT_VERSION}-${DISTRIBUTION_VERSION}
ARG EXTRA_PACKAGES
RUN apt update && apt -y install libsystemd-dev ${EXTRA_PACKAGES} && apt -y clean
