name: Build SDK for a given Swift version, distribution, and target architecture
description: This performs all the actions needed to generate a cross-compilation SDK.
inputs:
  swift-version:
    description: The version of Swift to use (.e.g., 5.9.2, 5.10.1, 6.0.3).
    required: true
  distribution-name:
    description: The name of the distribution to use for this SDK (e.g., ubuntu, rhel).
    required: true
  distribution-version:
    description: The version of the distribution to use for this SDK (e.g., jammy, bookworm, ubi9).
    required: true
  target-arch:
    description: The architecture to generate the SDK for (.e.g, x86_64, aarch64, armv7).
    required: true
runs:
  using: "composite"
  if: ${{ (inputs.target-arch == 'armv7' && inputs.distribution-name != 'rhel') || inputs.target-arch != 'armv7' }}
  steps:
  - name: Build SDK
    shell: bash
    run: TARGET_ARCH=${{ inputs.target-arch }} ./build-sdk.sh ${{ inputs.swift-version }} \
      ${{ inputs.distribution-name }} \
      ${{ inputs.distribution-version }}
  - name: Test SDK
    shell: bash
    run: TARGET_ARCH=${{ inputs.target-arch }} ./test-sdk.sh \
      ${{ inputs.swift-version }} \
      ${{ inputs.distribution-name }} \
      ${{ inputs.distribution-version }}
  - uses: actions/upload-artifact@v4
    name: Publish SDK
    with:
      name: artifacts-${{ inputs.swift-version }}-${{ inputs.distribution-name }}-${{ inputs.distribution-version }}-${{ inputs.target-arch }}
      path: |
        */*.deb
        */*.artifactbundle.tar.gz
